export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  llmProvider: process.env.FLOWOS_LLM_PROVIDER ?? "built-in",
  llmModel: process.env.FLOWOS_LLM_MODEL ?? "",
  embeddingModel: process.env.FLOWOS_EMBEDDING_MODEL ?? "flowos-deterministic-v1",
  llmApiKey: process.env.FLOWOS_LLM_API_KEY ?? "",
  demoMode: process.env.FLOWOS_DEMO_MODE !== "false",
};
